### ISSUE TITLE
Game Styles (1v1; 4v4; etc)

### ISSUE THREAD

**Issue by ConnorJC3** [realliance/senior-matchmaking#39]
For discussion: what game styles are in scope?

**Comment by ChristopherJMiller** [comment]
I forget where we left off in the discussions about it, but I believe 3v3 would be optimal given project scope. 3 players per team I believe is the minimal size to make teamwork interesting, allows the map to my scaled to something more appropriate for a mix of tactics and fps engagement, and is perfect for our situation as there is 5 of us on the team, so we only need to find one more person to try out full matches (we can grab Rob or something)

**Comment by ConnorJC3** [comment]
@ChristopherJMiller my reason for bringing this up is I believe in addition to whatever "big" game style we pick (3v3; 4v4; etc) we should also consider allowing 1v1s for these reasons:

- It makes one-off playtesting of new features _significantly_ easier (this is the primary reason imo)
- Lots of competitive or semi-competitive games in similar genres to ours have a 1v1 queue for players that really want to focus on their own gameplay
- Having at least 2 queue types will result in better abstractions in matchmaking
